sonar.projectKey=DougTrajano_vaultriever
sonar.projectName=vaultriever
sonar.organization=dougtrajano
sonar.sources=vaultriever
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12,3.13
sonar.python.coverage.reportPaths=coverage.xml
